name: Playwright Tests
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Setup dotnet
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 7.x
    - run: dotnet build BrainSpark/Client/BrainSpark.Client.E2ETests/BrainSpark.Client.E2ETests.csproj
    - name: Ensure browsers are installed
      run: pwsh bin/Debug/net7.0/playwright.ps1 install --with-deps
    - name: Run your tests
      run: dotnet test BrainSpark/Client/BrainSpark.Client.E2ETests/BrainSpark.Client.E2ETests.csproj
